# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CtxReleases < Formula
  desc "Project memory for AI agents"
  homepage "https://github.com/divitsheth/ctx-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_darwin_amd64.tar.gz"
      sha256 "b4f6ad14c30d6899e0577106e97b356472754b0740176e33145a3bae456e54df"

      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_darwin_arm64.tar.gz"
      sha256 "ebdc8eca8b9f365c9e8809f278941801bd46066e04dfe466c6052d1780ee97e3"

      define_method(:install) do
        bin.install "ctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_linux_amd64.tar.gz"
      sha256 "f78ce3a014fdee60959874b57b9c1535d918d3b77b5551ddb4867427dfd208e8"
      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_linux_arm64.tar.gz"
      sha256 "38dfda4432ffc74558f52063594e96b034463def02bfea948b788d49cb01cb0a"
      define_method(:install) do
        bin.install "ctx"
      end
    end
  end
end
