# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctx < Formula
  desc "Project memory for AI agents"
  homepage "https://github.com/divitsheth/ctx-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_darwin_amd64.tar.gz"
      sha256 "cde38caa8ff359f46074060ac1f6357bbfd554746a9dbe23e8547d791cbbb0dc"

      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_darwin_arm64.tar.gz"
      sha256 "a2726f116f914ba0e18d8d0de80e47024d7c55b89b2c4df00f8e36d5793a9231"

      define_method(:install) do
        bin.install "ctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_linux_amd64.tar.gz"
      sha256 "50dd312896d0cbe790dd4e6f09961143609747fbd4425233da543793c9db1544"
      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.0/ctx_0.1.0_linux_arm64.tar.gz"
      sha256 "5314c0eaa3689a2559b7f6be76a67c2428238e6823a6f1245956eb155de4c4b8"
      define_method(:install) do
        bin.install "ctx"
      end
    end
  end
end
