# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctx < Formula
  desc "Project memory for AI agents"
  homepage "https://github.com/divitsheth/ctx-releases"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.1/ctx_0.1.1_darwin_amd64.tar.gz"
      sha256 "7867c9a57646cb6ff002df2a40bb9a6e50b0ebe62045f5010b471428396ea546"

      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.1/ctx_0.1.1_darwin_arm64.tar.gz"
      sha256 "07b4c0743e66ad0c4f9965da53ebf711205fe69a279121a2d8bb06dab31ab099"

      define_method(:install) do
        bin.install "ctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.1/ctx_0.1.1_linux_amd64.tar.gz"
      sha256 "f002744ae8a36a08c740b2dc2430998f219b920973d1e631c9a869bf4ffe10d2"
      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.1/ctx_0.1.1_linux_arm64.tar.gz"
      sha256 "d34335af3201a0f20fa22dfc6bcc62a2a4b14a27722641d58c069103e535a544"
      define_method(:install) do
        bin.install "ctx"
      end
    end
  end
end
