# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctx < Formula
  desc "Project memory for AI agents"
  homepage "https://github.com/divitsheth/ctx-releases"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.2/ctx_0.1.2_darwin_amd64.tar.gz"
      sha256 "ac9bfa67235e1b6710922f9306f587af599fc7732a433ce80e01bfdade813769"

      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.2/ctx_0.1.2_darwin_arm64.tar.gz"
      sha256 "6f88eee7fa0467326efb022e8100cbea0709fd4ee578f8fb9d71fc7bc1e07514"

      define_method(:install) do
        bin.install "ctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.2/ctx_0.1.2_linux_amd64.tar.gz"
      sha256 "c7c73d9002de940c062238c9a78d1f870763feb41adf84f01f90819d507e1413"
      define_method(:install) do
        bin.install "ctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/divitsheth/ctx-releases/releases/download/v0.1.2/ctx_0.1.2_linux_arm64.tar.gz"
      sha256 "a8dc44473b6c2963b80b5cf01dad2e7856db974d9630e3adc0d168261bde9bd1"
      define_method(:install) do
        bin.install "ctx"
      end
    end
  end
end
